-- HH-063: the options page (Esc > Options > AddOns > HeadHunter).

return function(T, H)
    T.case("toggles read and write the settings the modules use", function()
        local ns = H.Boot({ client = "era" })
        local S = ns.SettingsPanel
        local alerts = S.Option("alerts")
        T.eq(S.Get(alerts), true, "alerts on by default")
        S.Set(alerts, false)
        T.eq(ns.db.settings.alerts.enabled, false, "written")
        T.eq(ns.Alerts:Show({ key = "x", chat = "hello" }), false, "alerts really off")
        S.Set(S.Option("tooltip"), false)
        T.eq(ns.TooltipLine:Enabled(), false, "tooltip line off")
        S.Set(S.Option("mapPins"), false)
        T.eq(ns.MapMarkers:Enabled(), false, "map pins off")
    end)

    T.case("minimap: the page says 'shown', the database keeps 'hidden'", function()
        local ns = H.Boot({ client = "era", minimap = true })
        local S = ns.SettingsPanel
        local minimap = S.Option("minimap")
        T.eq(S.Get(minimap), true, "shown")
        S.Set(minimap, false)
        T.eq(ns.db.settings.minimap.hidden, true, "hidden in the database")
        T.ok(not ns.MinimapButton:IsShown(), "button hidden at once")
        H.Slash("minimap")
        T.eq(S.Get(minimap), true, "/hh minimap and the page agree")
        T.ok(ns.MinimapButton:IsShown(), "shown again")
    end)

    T.case("range cycles; unknown choices are refused", function()
        local ns = H.Boot({ client = "era" })
        local S = ns.SettingsPanel
        local range = S.Option("range")
        T.eq(S.Get(range), "adjacent", "default")
        T.eq(S.NextChoice(range), "continent", "next")
        S.Set(range, S.NextChoice(range))
        T.eq(ns.db.settings.alerts.range, "continent", "written")
        T.eq(S.NextChoice(range), "adjacent", "wraps around")
        T.eq(S.Set(range, "everywhere"), false, "refused")
        T.eq(ns.db.settings.alerts.range, "continent", "unchanged")
    end)

    T.case("Serial Killer window stays within 5 to 15 minutes", function()
        local ns = H.Boot({ client = "era" })
        local S = ns.SettingsPanel
        local serial = S.Option("serial")
        T.eq(S.Get(serial), 15, "default")
        S.Set(serial, 16)
        T.eq(S.Get(serial), 15, "at most 15")
        S.Set(serial, 2)
        T.eq(S.Get(serial), 5, "at least 5")
        S.Set(serial, 9.7)
        T.eq(S.Get(serial), 9, "whole minutes")
    end)

    T.case("registered where the client allows it; /hh options opens it", function()
        local ns = H.Boot({ client = "forever", options = "settings" })
        T.eq(ns.SettingsPanel.registered, "settings", "Settings API")
        H.Slash("options")
        T.eq(H.optionsOpened, "HeadHunter", "opened by category")

        ns = H.Boot({ client = "era", options = "interface" })
        T.eq(ns.SettingsPanel.registered, "interface", "old options list")
        H.Slash("options")
        T.ok(H.optionsOpened ~= nil, "opened")

        ns = H.Boot({ client = "era" })
        T.eq(ns.SettingsPanel.registered, nil, "neither")
        H.Slash("options")
        T.ok(H.Printed("not available"), "said so")
        T.noErrors()
    end)

    T.case("two tabs: General has alerts, HeadHunter Sync and rules, Display the rest", function()
        local ns = H.Boot({ client = "forever", options = "settings" })
        local P = ns.SettingsPanel
        T.eq(P.PageOf("alerts"), "general", "alerts")
        T.eq(P.PageOf("screenshots"), "general", "HeadHunter Sync")
        T.eq(P.PageOf("serial"), "general", "rules")
        T.eq(P.PageOf("mapPins"), "display", "map pins")
        T.eq(P.page, "general", "opens on General")
        P:ShowPage("display")
        T.eq(P.page, "display", "switched")
        T.noErrors()
    end)
end
